mode = "dark"

accent = "#a86bff"
selection = "#3a245f"
muted = "#9185a5"

background = "#090711"
dark_background = "#050409"
darker_background = "#020204"
lighter_background = "#1c1630"

foreground = "#e5ddf2"
dark_foreground = "#9185a5"
light_foreground = "#f0e8fa"
bright_foreground = "#fff9ff"

red = "#ff5364"
yellow = "#d8b85a"
orange = "#f0804d"
green = "#72c58b"
cyan = "#5dcfd8"
blue = "#6b8dff"
magenta = "#c76cff"
brown = "#8a604a"

bright_red = "#ff7e8b"
bright_yellow = "#ead07b"
bright_green = "#98dbaa"
bright_cyan = "#86e6ed"
bright_blue = "#91aaff"
bright_magenta = "#dc9bff"

hyprland_active_border = "rgba(a86bffff) rgba(fff9ffff) rgba(6b8dffff) -32deg"
hyprland_inactive_border = "rgba(9185a555)"
active_border_color = "#a86bff"
active_tab_background = "#3a245f"
