background                = "#11150d"
background-alpha          = 0.93
text                      = "#dfd5ba"
border                    = "rgba(26b7c4ff) rgba(b978e8ff) rgba(d38932ff) 32deg"
border-alpha              = 1.0
border-width              = "1 6 4 2"
scrim                     = "#050704"
scrim-alpha               = 0.76
selected-background       = "#4b2b6e"
selected-background-alpha = 0.94
selected-text             = "#f6efd6"
selected-border           = "rgba(d38932ff) rgba(26b7c4ff) rgba(b978e8ff) -48deg"
selected-border-alpha     = 1.0
selected-border-width     = "3 1 6 1"
