background                = "#ede9db"
background-alpha          = 0.97
text                      = "#182018"
border                    = "rgba(087882ff) rgba(744a93ff) rgba(c3a24bff) 32deg"
border-alpha              = 1.0
border-width              = "1 5 4 2"
scrim                     = "#ddd7c7"
scrim-alpha               = 0.64
selected-background       = "#c3a24b"
selected-background-alpha = 0.88
selected-text             = "#101510"
selected-border           = "rgba(c3a24bff) rgba(087882ff) -42deg"
selected-border-alpha     = 1.0
selected-border-width     = "3 1 6 1"
