background                = "#07111f"
background-alpha          = 0.94
text                      = "#eddfc9"
border                    = "rgba(ec2b9aff) rgba(29bec4ff) rgba(e8791cff) -35deg"
border-alpha              = 1.0
border-width              = "4 1 7 4"
scrim                     = "#02050a"
scrim-alpha               = 0.78
selected-background       = "#135565"
selected-background-alpha = 0.94
selected-text             = "#fff4e2"
selected-border           = "rgba(e8791cff) rgba(ec2b9aff) rgba(29bec4ff) 28deg"
selected-border-alpha     = 1.0
selected-border-width     = "2 6 2 1"
