background                = "#050608"
background-alpha          = 0.95
text                      = "#f1dec7"
border                    = "rgba(20cbd2ff) rgba(ff4ba2ff) rgba(ff7a24ff) 40deg"
border-alpha              = 1.0
border-width              = "7 1 2 5"
scrim                     = "#020304"
scrim-alpha               = 0.82
selected-background       = "#20cbd2"
selected-background-alpha = 0.92
selected-text             = "#020304"
selected-border           = "rgba(ff4ba2ff) rgba(20cbd2ff) -40deg"
selected-border-alpha     = 1.0
selected-border-width     = "1 1 7 2"
