background       = "#030807"
background-alpha = 0.96
text             = "#d7e4db"
border           = "rgba(00d7c4ff) rgba(ff7a1aff) rgba(4ea1ffff) 72deg"
border-alpha     = 1.0
border-width     = "1 8 4 2"
